version: '3.4'

services:
  api:
    container_name: api
    build: .
    command: npm start
    hostname: api
    ports:
      - 3000:3000
    environment:
      - PORT=3000
    networks:
      - loadtest

  k6:
    container_name: k6
    image: loadimpact/k6
    environment:
      - LOCAL_API_URL=http://api:3000
    volumes:
      - ./tests:/tests
    stop_signal: SIGKILL
    network_mode: host

networks:
  loadtest:
