version: '3.4'

services:
  api:
    container_name: api
    build: .
    command: npm start
    hostname: api
    ports:
      - 5000:5000
    environment:
      - PORT=5000
    networks:
      - loadtest

  k6:
    container_name: k6
    image: loadimpact/k6
    environment:
      - LOCAL_API_URL=http://api:5000
    volumes:
      - ./tests:/tests
    stop_signal: SIGKILL
    networks:
      - loadtest

  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    env_file:
      - 'env.influxdb'
    volumes:
      - /srv/docker/influxdb/data:/var/lib/influxdb
    networks:
      - loadtest

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    env_file:
      - 'env.grafana'
    ports:
      - 3000:3000
    user: '0'
    volumes:
      - /srv/docker/grafana/data:/var/lib/grafana
    networks:
      - loadtest

networks:
  loadtest:
